
    ; ATOM S3 — 顔画像4枚ループ表示
[env:atom-s3]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    m5stack/M5Unified@^0.2.2

board_build.partitions = huge_app.csv
board_build.filesystem = spiffs
